class CreateForms < ActiveRecord::Migration
  def change
    create_table :forms do |t|
    	t.string :user_fname
    	t.string :user_lname
    	t.integer :passcode, :unique => true
    	t.string :gh_ami_cc_only, default: "0"
        t.string :gh_ami_cc_plus, default: "0"
        t.string :gh_ami_reg_med, default: "0"
        t.string :gh_ami_invasive, default: "0"
        t.string :gh_ami_respirator, default: "0"
        t.string :gh_ami_dialysis, default: "0"
        t.string :gh_ami_cpr, default: "0"
        t.string :gh_bi_cc_only, default: "0"
        t.string :gh_bi_cc_plus, default: "0"
        t.string :gh_bi_reg_med, default: "0"
        t.string :gh_bi_invasive, default: "0"
        t.string :gh_bi_respirator, default: "0"
        t.string :gh_bi_dialysis, default: "0"
        t.string :gh_bi_cpr, default: "0"
        t.string :dh_ami_cc_only, default: "0"
        t.string :dh_ami_cc_plus, default: "0"
        t.string :dh_ami_reg_med, default: "0"
        t.string :dh_ami_invasive, default: "0"
        t.string :dh_ami_respirator, default: "0"
        t.string :dh_ami_dialysis, default: "0"
        t.string :dh_ami_cpr, default: "0"
        t.string :dh_bi_cc_only, default: "0"
        t.string :dh_bi_cc_plus, default: "0"
        t.string :dh_bi_reg_med, default: "0"
        t.string :dh_bi_invasive, default: "0"
        t.string :dh_bi_respirator, default: "0"
        t.string :dh_bi_dialysis, default: "0"
        t.string :dh_bi_cpr, default: "0"
        t.string :esmc_ami_cc_only, default: "0"
        t.string :esmc_ami_cc_plus, default: "0"
        t.string :esmc_ami_reg_med, default: "0"
        t.string :esmc_ami_invasive, default: "0"
        t.string :esmc_ami_respirator, default: "0"
        t.string :esmc_ami_dialysis, default: "0"
        t.string :esmc_ami_cpr, default: "0"
        t.string :esmc_bi_cc_only, default: "0"
        t.string :esmc_bi_cc_plus, default: "0"
        t.string :esmc_bi_reg_med, default: "0"
        t.string :esmc_bi_invasive, default: "0"
        t.string :esmc_bi_respirator, default: "0"
        t.string :esmc_bi_dialysis, default: "0"
        t.string :esmc_bi_cpr, default: "0"
        t.string :nhi_ami_cc_only, default: "0"
        t.string :nhi_ami_cc_plus, default: "0"
        t.string :nhi_ami_reg_med, default: "0"
        t.string :nhi_ami_invasive, default: "0"
        t.string :nhi_ami_respirator, default: "0"
        t.string :nhi_ami_dialysis, default: "0"
        t.string :nhi_ami_cpr, default: "0"
        t.string :nhi_bi_cc_only, default: "0"
        t.string :nhi_bi_cc_plus, default: "0"
        t.string :nhi_bi_reg_med, default: "0"
        t.string :nhi_bi_invasive, default: "0"
        t.string :nhi_bi_respirator, default: "0"
        t.string :nhi_bi_dialysis, default: "0"
        t.string :nhi_bi_cpr, default: "0"
    end
  end
end
